### ISSUE TITLE
Handle --random

### ISSUE THREAD

**Issue by Natim** [luki/caesarcy.rs#11]
It would be nice to add a `--random` option to the CLI tool to choose an offset automatically.

The offset could be returned as the CLI exit code.

**Comment by suesslin** [comment]
I like the idea! I'll try myself on that.

**Comment by Natim** [comment]
Oh sorry I just filed the PR: https://github.com/caesarlib/caesarlib.rs/pull/12

However I found an interesting bug, because `rand::thread_rng<i32>()` was returning negative number sometimes and this was failing the encipher and decipher command.

We can either use u16 unsigned integer or make encipher and decipher to support negative offsets. #13

**Comment by suesslin** [comment]
@Natim What would also have been possible is just taking it square and then the root of that to make it mathematical 😄

**Comment by Natim** [comment]
Or its absolute value. http://stackoverflow.com/a/27183279/186202
