### ISSUE TITLE
Encipher/decipher at 1 & 2 ... causes strange behaviour

### ISSUE THREAD

**Issue by suesslin** [luki/caesarcy.rs#17]
As noticed by @Natim 

Working on the algorithm :)

**Comment by Natim** [comment]
Refs https://github.com/caesarlib/caesarlib.rs/pull/16

**Comment by Natim** [comment]
It is a shame that you didn't do a PR so that we could review what you did.
Apparently you change the args from the CLI tool, please update the README documentation accordingly.

**Comment by suesslin** [comment]
@Natim I am sorry! I have never worked in a team I must admit. I will do pull requests from now on! :)

**Comment by Natim** [comment]
No worries, it is just a project for fun, I like the way you take feedback 👍
